# Generated by Django 5.1.15 on 2026-04-09 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0060_add_allow_skip_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="review_comment",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="QA review comment (required on rejection)",
                null=True,
                verbose_name="review comment",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="QA review status: pending, accepted, or rejected",
                max_length=16,
                verbose_name="review status",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the annotation was reviewed",
                null=True,
                verbose_name="reviewed at",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="QA user who reviewed this annotation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
